# Generated by Django 5.0.6 on 2024-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
