# Generated by Django 5.0.6 on 2024-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
